import React, { ChangeEvent, MouseEvent, useState } from 'react';
import { useSetRecoilState } from "recoil";
import { todosState } from '../state';

export const NewTodo: React.FC = () => {
  const [todoName, setTodoName] = useState("");
  const setTodos = useSetRecoilState(todosState);

  const onChange = (e: ChangeEvent<HTMLInputElement>) => {
    let todoName = e.target.value;
    setTodoName(todoName);
  };

  const onSave = (e: MouseEvent<HTMLInputElement>): void => {
    e.preventDefault();
    setTodos(todoList => [...todoList, {
      //Random Autogenerated ID
      id: Math.random().toString(32).substr(2, 9),
      name: todoName,
      completed: false
    }]);
  };

  return (
    <div>
      <input type="text" onChange={onChange} />
      <input type="button" value="Add" onClick={onSave} />
    </div>
  );
}


